Change structure project for "cazanw" binary at installation of cazanw with "npm install"
Sellig6792/cazanw pull request #4
Opened 2024-04-27 20:46 UTC by Sellig6792

2024-04-27 21:27 UTC, hamirmahal requested changes

2024-04-27 21:27 UTC, hamirmahal commented on post-build/src/cazanw.js
> +}
```suggestion
function getWhichTarget() {
  if (platform === "darwin") {
    return arch === "arm64" ? "aarch64-apple-darwin" : "x86_64-apple-darwin";
  }

  if (platform === "win32") {
    return arch === "arm64"
      ? "aarch64-pc-windows-msvc"
      : "x86_64-pc-windows-gnu";
  }

  if (platform === "linux") {
    return arch === "arm64"
      ? "aarch64-unknown-linux-gnu"
      : "x86_64-unknown-linux-gnu";
  }

  throw new Error(`Unsupported platform or architecture: ${platform} ${arch}`);
}
```

2024-04-27 21:31 UTC, Sellig6792 commented
Anything else @hamirmahal 😄😄?

2024-04-27 21:34 UTC, hamirmahal commented on post-build/src/main.rs
> +fn open_package_json() -> serde_json::Map<String, serde_json::Value> {
Hmm... I don't see an import for `serde_json`. Is that intentional?

2024-04-27 21:40 UTC, Sellig6792 commented on post-build/src/main.rs
> +fn open_package_json() -> serde_json::Map<String, serde_json::Value> {
In this file: `post-build/Cargo.toml`

2024-04-28 09:25 UTC, Sellig6792 commented
I'll implement the prebuild before merging the PR

2024-04-28 09:25 UTC, closed without merging